/**
 * Ecom API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GrantedAuthority } from './grantedAuthority';


export interface JwtResponse { 
    token?: string;
    roles?: Array<GrantedAuthority>;
}

