/**
 * Ecom API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderItemRequest } from './orderItemRequest';


export interface OrderRequest { 
    list?: Array<OrderItemRequest>;
    name?: string;
    email?: string;
}

